name: project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Versioning information
version: 1.0.0+1

environment:
    sdk: ">=3.0.0 <4.0.0"  # تم تحديثه ليكون متوافقًا مع Flutter 3.x

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  lottie: ^3.3.1
  pinput: ^5.0.1
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.1 
  firebase_storage: ^12.4.0
  firebase_messaging: ^15.2.0
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  file_picker: ^8.1.7
  provider: ^6.0.0
  shared_preferences: ^2.0.8
  permission_handler: ^11.3.1
  flutter_slidable: ^4.0.0
  uuid: ^4.5.1
  timeline_tile: ^2.0.0
  flutter_plugin_android_lifecycle: ^2.0.24
  firebase_core: ^3.10.1
  google_sign_in_web: ^0.12.4+3
  device_info_plus: ^11.2.2
  timeago: ^3.7.0
  fl_chart: ^0.70.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/product_1.png
    - assets/img/product_2.png
    - assets/img/product_3.png
    - assets/img/product_4.png
    - assets/img/product_5.png
    - assets/img/product_6.png
    - assets/img/product_7.png
    - assets/img/product_8.png
    - assets/img/google_icon.png
    - assets/img/client-handshake.jpg
    - assets/img/login.png
    - assets/img/9game_logo.png
    - assets/animation/empty_cart.json
    - assets/animation/success.json
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        
